{{- if and .Values.oidcMock.enabled .Values.oidcMock.authorizeUrl (not .Values.hbbs.oauth2.existingSecret) }}
{{- $tokenUrl := printf "http://%s:%v" (include "rustdesk.componentName" (dict "context" . "component" "oidc-mock")) .Values.oidcMock.port -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hbbs-oauth2
  labels:
    {{- include "rustdesk.labels" (dict "context" . "component" "hbbs") | nindent 4 }}
stringData:
  oauth2.toml: |
    [[provider]]
    provider = "Dex"
    authorization_url = "{{ .Values.oidcMock.authorizeUrl }}/authorize"
    token_exchange_url = "{{ $tokenUrl }}/token"
    app_id = "rustdesk-api"
    app_secret = "appsecret"
    scope = "openid email profile"
    op_auth_string = "oidc/OIDC"
    op = "OIDC"
    issuer = "{{ .Values.oidcMock.authorizeUrl }}"
{{- end }}
