{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rustdesk.serviceAccountName" . }}
  labels:
    {{- include "rustdesk.labels" (dict "context" . "component" "rustdesk") | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
